import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  DATABASE_URL: z.string().min(1, "DATABASE_URL is required"),
  DIRECT_URL: z.string().optional(),
  NEXTAUTH_SECRET: z.string().min(16, "NEXTAUTH_SECRET must be at least 16 characters"),
  NEXTAUTH_URL: z.string().url().optional().default("http://localhost:3000"),
  INITIAL_SUPER_ADMIN_EMAIL: z.string().email().optional().default("admin@softlabglobal.com"),
  INITIAL_SUPER_ADMIN_PASSWORD: z.string().min(8).optional(),
  INITIAL_SUPER_ADMIN_NAME: z.string().optional().default("Super Administrator"),
  SEED_SUPER_ADMIN_PASSWORD: z.string().min(8).optional(),
  SEED_TRAINER_PASSWORD: z.string().min(8).optional(),
  SEED_STUDENT_PASSWORD: z.string().min(8).optional(),
  RESET_SEED_PASSWORDS: z.string().optional().default("false"),
  NEXT_PUBLIC_APP_URL: z.string().url().optional().default("http://localhost:3000"),
  NEXT_PUBLIC_APP_NAME: z.string().optional().default("SOFTLAB GLOBAL"),
  NEXT_PUBLIC_SUPPORT_PHONE: z.string().optional().default("9194085890"),
  NEXT_PUBLIC_SUPPORT_EMAIL: z.string().email().optional().default("info@softlabglobal.com"),
  PAYMENT_PROVIDER: z.string().optional().default("RAZORPAY"),
  RAZORPAY_KEY_ID: z.string().optional().default(""),
  RAZORPAY_KEY_SECRET: z.string().optional().default(""),
  RAZORPAY_WEBHOOK_SECRET: z.string().optional().default(""),
  NEXT_PUBLIC_RAZORPAY_KEY_ID: z.string().optional().default(""),
});

export const env = envSchema.parse({
  NODE_ENV: process.env.NODE_ENV,
  DATABASE_URL: process.env.DATABASE_URL,
  DIRECT_URL: process.env.DIRECT_URL || process.env.DATABASE_URL,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  INITIAL_SUPER_ADMIN_EMAIL: process.env.INITIAL_SUPER_ADMIN_EMAIL,
  INITIAL_SUPER_ADMIN_PASSWORD: process.env.INITIAL_SUPER_ADMIN_PASSWORD,
  INITIAL_SUPER_ADMIN_NAME: process.env.INITIAL_SUPER_ADMIN_NAME,
  SEED_SUPER_ADMIN_PASSWORD: process.env.SEED_SUPER_ADMIN_PASSWORD,
  SEED_TRAINER_PASSWORD: process.env.SEED_TRAINER_PASSWORD,
  SEED_STUDENT_PASSWORD: process.env.SEED_STUDENT_PASSWORD,
  RESET_SEED_PASSWORDS: process.env.RESET_SEED_PASSWORDS,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_SUPPORT_PHONE: process.env.NEXT_PUBLIC_SUPPORT_PHONE,
  NEXT_PUBLIC_SUPPORT_EMAIL: process.env.NEXT_PUBLIC_SUPPORT_EMAIL,
  PAYMENT_PROVIDER: process.env.PAYMENT_PROVIDER || "RAZORPAY",
  RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID || process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID || "",
  RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET || "",
  RAZORPAY_WEBHOOK_SECRET: process.env.RAZORPAY_WEBHOOK_SECRET || "",
  NEXT_PUBLIC_RAZORPAY_KEY_ID: process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID || process.env.RAZORPAY_KEY_ID || "",
});
