export interface ServiceMilestone {
  percentage: string;
  stage: string;
  description: string;
}

export interface ServicePackageItem {
  id: string;
  categoryCode: string;
  categoryName: string;
  title: string;
  tagline: string;
  pricingDisplay: string;
  billingType: "ONE_TIME" | "MONTHLY" | "ANNUAL" | "CUSTOM";
  priceNote?: string;
  timeline?: string;
  idealFor: string;
  deliverables: string[];
  paymentStructure: {
    type: "PROJECT_MILESTONES" | "MONTHLY_ADVANCE" | "ANNUAL_CONTRACT" | "DIRECT_SUBSCRIPTION";
    title: string;
    description: string;
    milestones: ServiceMilestone[];
  };
  commercialTerms?: string[];
  badge?: string;
  isPopular?: boolean;
}

export const PAYMENT_STRUCTURES = {
  PROJECT_WORK: {
    type: "PROJECT_MILESTONES" as const,
    title: "4-Stage Project Milestone Structure",
    description: "Tied strictly to verified development deliverables and client sign-offs.",
    milestones: [
      { percentage: "40%", stage: "Advance Initiation", description: "Payable on project confirmation, scope lock & work kickoff." },
      { percentage: "30%", stage: "Prototype & Architecture Approval", description: "Payable upon Figma UI/UX approval & system architecture demo." },
      { percentage: "20%", stage: "UAT & Staging Deployment", description: "Payable upon test environment demo, feature testing & client review." },
      { percentage: "10%", stage: "Final Production Go-Live", description: "Payable upon final production deployment, source handover & live launch." },
    ],
  },
  MONTHLY_RETAINER: {
    type: "MONTHLY_ADVANCE" as const,
    title: "Monthly Advance Retainer Structure",
    description: "Predictable, ongoing sprint allocation for dedicated engineering & marketing squads.",
    milestones: [
      { percentage: "100%", stage: "Advance Monthly Retainer", description: "Payable at the beginning of each billing month. Invoices raised on the 1st, payable within 5 working days." },
    ],
  },
  ANNUAL_RETAINER: {
    type: "ANNUAL_CONTRACT" as const,
    title: "Annual Staged Contract or 100% Upfront Discount",
    description: "Annual SLA stability with staged quarterly milestone payments or instant 10% annual savings.",
    milestones: [
      { percentage: "50%", stage: "Contract Signing Advance", description: "Payable upon annual contract execution." },
      { percentage: "25%", stage: "Quarter 2 Milestone", description: "Payable at the start of month 4." },
      { percentage: "25%", stage: "Quarter 3 Milestone", description: "Payable at the start of month 7." },
    ],
  },
  DIRECT_SUBSCRIPTION: {
    type: "DIRECT_SUBSCRIPTION" as const,
    title: "Annual/Monthly Direct Provisioning",
    description: "100% upfront provisioning with official GST tax invoice and SLA certificate.",
    milestones: [
      { percentage: "100%", stage: "Provisioning Payment", description: "Payable upon cloud license registration & domain/server lock." },
    ],
  },
};

export const COMMON_COMMERCIAL_TERMS = [
  "All quoted prices are exclusive of 18% GST (Goods and Services Tax).",
  "Ad spend budgets (Google Ads, Meta Ads, LinkedIn Ads) are funded directly by the client or invoiced at actuals.",
  "Third-party API charges, payment gateway fees, SMS DLT credits, and WhatsApp Cloud API costs are billed at actuals.",
  "Full intellectual property rights and production source code handover are completed upon final milestone settlement.",
  "Standard support window applies post-launch with direct ticket escalation.",
];

export const CORPORATE_SLA_TIERS = [
  {
    name: "Basic SLA",
    responseTime: "24–48 Hours",
    channels: "Email & Web Ticket Support",
    uptimeTarget: "99.0% Uptime",
    bestFor: "Informational websites and low-criticality internal portals",
  },
  {
    name: "Professional SLA",
    responseTime: "8–24 Hours",
    channels: "Dedicated WhatsApp Group + Phone + Email",
    uptimeTarget: "99.5% Uptime",
    bestFor: "High-traffic e-commerce, active business apps & customer portals",
  },
  {
    name: "Enterprise SLA",
    responseTime: "2–8 Hours (Immediate Critical Escalation)",
    channels: "24/7 Dedicated Account Manager + Hotline + Video War Room",
    uptimeTarget: "99.9% Uptime Guarantee",
    bestFor: "Mission-critical ERPs, SaaS platforms, banking/payment flows & corporate groups",
  },
];

/* -------------------------------------------------------------
   01. WEBSITE DEVELOPMENT PACKAGES
------------------------------------------------------------- */
export const WEBSITE_PACKAGES: ServicePackageItem[] = [
  {
    id: "web-starter",
    categoryCode: "WEB_DEV",
    categoryName: "Website Development",
    title: "Starter Website",
    tagline: "Essential Online Presence for Fast Credibility",
    pricingDisplay: "₹24,999 + GST",
    billingType: "ONE_TIME",
    priceNote: "One-Time Project Investment",
    timeline: "7 – 15 Working Days",
    idealFor: "Small businesses, individual consultants, coaching institutes and solo professionals.",
    deliverables: [
      "Up to 5 custom-designed responsive pages (Home, About, Services, Contact, Gallery/Team)",
      "100% Mobile, tablet & desktop responsive layout",
      "One-click WhatsApp floating chat & click-to-call integration",
      "Interactive lead capture contact form with instant email alerts",
      "Google Maps location embed & official contact badge",
      "Social media profile integration & live links",
      "Foundational on-page SEO setup (Meta titles, descriptions, OpenGraph tags)",
      "Complimentary SSL setup & HTTPS security encryption",
      "Google Analytics 4 setup & basic traffic tracking",
      "Basic page speed optimization & asset compression",
      "2 rounds of design revisions",
      "15 days of post-launch warranty & technical bug-fix support",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Budget Friendly",
  },
  {
    id: "web-business",
    categoryCode: "WEB_DEV",
    categoryName: "Website Development",
    title: "Business Website",
    tagline: "High-Converting Corporate Web Engine",
    pricingDisplay: "₹49,999 + GST",
    billingType: "ONE_TIME",
    priceNote: "One-Time Project Investment",
    timeline: "15 – 30 Working Days",
    idealFor: "Growing SMEs, schools, healthcare clinics, manufacturing companies, and regional corporate offices.",
    deliverables: [
      "Up to 10 custom-crafted high-performance pages",
      "Tailored corporate UI/UX crafted to institutional branding",
      "Dynamic lead generation forms with field validation & anti-spam honeypot",
      "Integrated WhatsApp live chat widget & telephone CTA routing",
      "Dynamic Blog & Corporate News engine with easy CMS publishing",
      "Careers / Job Vacancies board with resume submission capability",
      "Interactive Client Testimonials & Portfolio / Project case-study showcase",
      "Comprehensive On-Page SEO optimization & keyword hierarchy",
      "Core Web Vitals speed tuning (LCP < 2.5s, mobile caching)",
      "SSL certificate installation, security headers & HTTP hardening",
      "Google Search Console & Google Analytics 4 integration with sitemap submission",
      "3 rounds of design reviews & refinement sprints",
      "30 days of comprehensive post-launch warranty support",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Most Popular",
    isPopular: true,
  },
  {
    id: "web-corporate",
    categoryCode: "WEB_DEV",
    categoryName: "Website Development",
    title: "Professional Corporate Website",
    tagline: "Enterprise-Grade Digital Flagship",
    pricingDisplay: "₹99,999 + GST",
    billingType: "ONE_TIME",
    priceNote: "One-Time Project Investment",
    timeline: "30 – 45 Working Days",
    idealFor: "Mid-sized enterprises, multi-location companies, corporate brands, and institutions demanding high-trust visual positioning.",
    deliverables: [
      "Up to 20 bespoke pages with tailored modular sections",
      "High-end bespoke UI/UX prototyping in Figma with design tokens",
      "Smooth micro-interactions, scroll animations & interactive data displays",
      "Multi-step lead qualification forms with automated CRM notification webhooks",
      "Headless CMS integration for frictionless in-house content editing",
      "Multi-branch & multi-department dedicated location landing pages",
      "Full HR Career Portal with applicant tracking & PDF resume uploads",
      "Advanced On-Page SEO, Schema.org rich snippet markup & breadcrumbs",
      "Next.js / edge-optimized server rendering for sub-second global load times",
      "Enterprise security hardening, DDoS shields & automated daily cloud backups",
      "Google Analytics 4 + Google Tag Manager + Search Console advanced event tracking",
      "4 rounds of architectural & visual revisions",
      "45 days of priority post-launch support with dedicated technical lead",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Enterprise Grade",
  },
  {
    id: "web-ecommerce",
    categoryCode: "WEB_DEV",
    categoryName: "Website Development",
    title: "E-Commerce Website",
    tagline: "High-Speed Direct-to-Consumer & B2B Sales Engine",
    pricingDisplay: "₹1,49,999 + GST",
    billingType: "ONE_TIME",
    priceNote: "One-Time Project Investment",
    timeline: "30 – 60 Working Days",
    idealFor: "Retail brands, manufacturers, distributors, and direct-to-consumer businesses selling across India and globally.",
    deliverables: [
      "Initial setup and upload of up to 100 products with variants (size, color, SKU)",
      "High-converting modern storefront with mobile-first checkout",
      "Dynamic product catalogue, multi-level category taxonomy & faceted filters",
      "AJAX sliding shopping cart, discount coupons & seasonal flash-sale promo codes",
      "Multi-gateway checkout integration (Razorpay, Cashfree, PayU, Stripe & UPI QR)",
      "Automated logistics & courier API integration readiness (Shiprocket / Delhivery)",
      "Registered customer dashboard with live order history, downloads & reorder",
      "Full-featured Admin Order Management & Dispatch status workflow",
      "Automated low-inventory alerts and stock notifications",
      "Instant WhatsApp & SMS order confirmation alerts to customers & dispatch",
      "Automated Abandoned Cart notification & recovery mechanism",
      "Product-level schema rich snippets for Google Merchant Center readiness",
      "PCI-DSS compliant SSL security hardening & DDoS defense",
      "60 days of post-launch stabilization & technical warranty support",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "High Growth",
  },
  {
    id: "web-custom",
    categoryCode: "WEB_DEV",
    categoryName: "Website Development",
    title: "Custom Web Platform / Web Application",
    tagline: "Bespoke SaaS Architectures & Enterprise Portals",
    pricingDisplay: "From ₹2,49,999 + GST",
    billingType: "CUSTOM",
    priceNote: "Tailored to Specific Architectural Scope",
    timeline: "45 – 90+ Working Days",
    idealFor: "Startups, SaaS companies, and institutions requiring complex multi-tenant portals, custom algorithms, role matrices, and deep third-party integrations.",
    deliverables: [
      "Ground-up Next.js 15 / React / TypeScript full-stack cloud architecture",
      "Role-Based Access Control (Super Admin, Manager, Staff, End Customer)",
      "Interactive data visualization dashboards with exportable CSV / PDF reports",
      "RESTful / tRPC / GraphQL API services with JWT & OAuth 2.0 authentication",
      "PostgreSQL / MySQL relational database with Prisma ORM migrations",
      "Automated CI/CD pipelines, containerization (Docker) & cloud deployment",
      "Real-time event streaming via WebSockets / Server-Sent Events",
      "Complete technical architecture documentation & API specification swagger",
      "Full IP and source code repository transfer to client organisation",
      "Custom SLA support agreement with dedicated engineering sprint team",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Bespoke Engineering",
  },
];

/* -------------------------------------------------------------
   02. SOFTWARE DEVELOPMENT TIERS & MODULES
------------------------------------------------------------- */
export const SOFTWARE_TIERS: ServicePackageItem[] = [
  {
    id: "soft-basic",
    categoryCode: "SOFTWARE_DEV",
    categoryName: "Software Development",
    title: "Basic Business Software",
    tagline: "Core Invoicing, Accounting & Workflow Digitization",
    pricingDisplay: "Starting from ₹75,000 + GST",
    billingType: "ONE_TIME",
    timeline: "20 – 35 Working Days",
    idealFor: "Retailers, small distributors, trading firms & clinics replacing manual pen-paper or Excel records.",
    deliverables: [
      "Custom billing, GST invoicing & automated tax calculations",
      "Customer / client contact registry & payment ledger",
      "Basic product / inventory catalog with stock in/out logging",
      "Daily transaction summaries & revenue reports",
      "Single-branch deployment with admin & operator roles",
      "Local/Cloud automated database backup script",
      "30 days post-deployment warranty support",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
  },
  {
    id: "soft-pro",
    categoryCode: "SOFTWARE_DEV",
    categoryName: "Software Development",
    title: "Professional Business Software",
    tagline: "Multi-Role Operational & CRM Hub",
    pricingDisplay: "Starting from ₹1,50,000 + GST",
    billingType: "ONE_TIME",
    timeline: "35 – 50 Working Days",
    idealFor: "Mid-sized distribution agencies, coaching academies, service centers & commercial companies.",
    deliverables: [
      "End-to-end CRM lead pipeline tracking & staff lead assignment",
      "Multi-user role-based permissions (Super Admin, Branch Manager, Staff)",
      "Automated payment reminders with WhatsApp & SMS notifications",
      "Comprehensive inventory tracking with low-stock warnings",
      "Staff attendance tracking & basic payroll calculations",
      "Interactive analytics dashboard with graphical revenue trends",
      "Exportable financial & operational reports (Excel / PDF)",
      "45 days dedicated warranty support",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "High ROI",
  },
  {
    id: "soft-advanced",
    categoryCode: "SOFTWARE_DEV",
    categoryName: "Software Development",
    title: "Advanced Business Software",
    tagline: "High-Volume Multi-Branch Workflow Suite",
    pricingDisplay: "Starting from ₹3,00,000 + GST",
    billingType: "ONE_TIME",
    timeline: "50 – 75 Working Days",
    idealFor: "Multi-location institutions, healthcare networks, franchised chains, and logistics companies.",
    deliverables: [
      "Centralized multi-branch synchronization with cross-location reporting",
      "Dynamic workflow engine with approval hierarchies",
      "Automated biometric attendance device integration",
      "Vendor purchase orders, goods receipt notes (GRN) & supplier ledgers",
      "Customer self-service portal for receipts and support requests",
      "Comprehensive audit trail logs capturing every edit and deletion",
      "Cloud database replication & failover safeguards",
      "60 days post-go-live hypercare support",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
  },
  {
    id: "soft-erp-crm",
    categoryCode: "SOFTWARE_DEV",
    categoryName: "Software Development",
    title: "Custom ERP / CRM System",
    tagline: "Enterprise Resource Architecture",
    pricingDisplay: "Starting from ₹3,00,000 + GST",
    billingType: "ONE_TIME",
    timeline: "60 – 90 Working Days",
    idealFor: "Educational institutions, universities, factories, manufacturing plants, and corporate groups.",
    deliverables: [
      "Unified enterprise modules: Admissions, HRMS, Invoicing, Procurement & Assets",
      "Lead scoring, telecalling queues with call logging & conversion funnels",
      "Custom rule engines for fee installments, penalties & discounts",
      "Batch management, scheduling & faculty assignment matrices",
      "Automated multi-gateway reconciliation with bank settlement feeds",
      "Granular role matrices down to individual column view/edit rights",
      "Executive KPI dashboards with real-time financial health graphs",
      "Complete employee training & operating system manuals",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Enterprise Standard",
  },
  {
    id: "soft-saas",
    categoryCode: "SOFTWARE_DEV",
    categoryName: "Software Development",
    title: "Custom SaaS Product",
    tagline: "Multi-Tenant Scalable Cloud Platform",
    pricingDisplay: "Starting from ₹5,00,000 + GST",
    billingType: "CUSTOM",
    timeline: "75 – 120 Working Days",
    idealFor: "Tech founders, institutional venture builders, and companies launching subscription-based digital products.",
    deliverables: [
      "Multi-tenant schema architecture with strict tenant data isolation",
      "Automated subscription billing, recurring debit mandates & tiered seat licenses",
      "White-label subdomains & custom branded tenant portals",
      "Public REST/GraphQL API for third-party developer integrations",
      "Event-driven microservices / serverless architecture",
      "Automated tenant onboarding with self-service checkout",
      "Multi-region deployment on AWS / DigitalOcean with auto-scaling",
      "Complete technical documentation & developer SDK guides",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
  },
  {
    id: "soft-enterprise",
    categoryCode: "SOFTWARE_DEV",
    categoryName: "Software Development",
    title: "Enterprise Solution",
    tagline: "Mission-Critical Institutional Digital Infrastructure",
    pricingDisplay: "Starting from ₹8,00,000 + GST",
    billingType: "CUSTOM",
    timeline: "90 – 150+ Working Days",
    idealFor: "Large conglomerate corporations, government bodies, hospitals, and banking/fintech institutions.",
    deliverables: [
      "High-availability distributed database cluster with zero-downtime failover",
      "Custom AI workflow automation & predictive analytics models",
      "Enterprise Single Sign-On (SAML, Okta, Microsoft Entra ID)",
      "Compliance audit readiness (ISO 27001, SOC2, HIPAA/DPDP data privacy)",
      "Disaster recovery site with automated RPO < 15 mins, RTO < 1 hour",
      "Dedicated agile sprint team (Architect, Frontend, Backend, QA Lead, DevOps)",
      "Formal corporate SLA agreement with 2-hour emergency escalation hotline",
      "Complete source code escrow & corporate IP assignment",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Institutional Flagship",
  },
];

export const SOFTWARE_MODULES_LIST = [
  "Student Management System (Admissions, Batches, Roll Numbers, Enrollment)",
  "Employee & HRMS (Profiles, Contracts, Hierarchy, Designations)",
  "Lead & CRM Pipeline (Source Attribution, Telecalling Queues, Follow-ups)",
  "Billing, Invoicing & GST (Automated Tax, HSN Codes, E-Invoices)",
  "Inventory & Stock Management (Stock Levels, Alerts, Suppliers, SKUs)",
  "Fees & Payment Tracking (Installment Schedules, Due Alerts, Online Gateways)",
  "Task & Project Management (Kanban, Milestones, Sprints, Deliverables)",
  "Attendance & Biometric Sync (Thumb/Face Recognition, Overtime, Leaves)",
  "Multi-Branch Administration (Centralized Controls, Inter-branch Transfers)",
  "Role-Based Access Control (Granular Permission Matrices, Action Logs)",
  "Reports & Analytics Dashboard (Revenue, Growth, Attrition, Projections)",
  "WhatsApp & SMS Automated Triggers (Receipts, Dues, Welcomes, Offers)",
  "Customer & Client Portal (Self-Service Dashboard, Receipts, Tickets)",
  "Vendor & Procurement Management (Purchase Orders, Inward Goods, Ledgers)",
  "Digital Document Locker (Secure File Uploads, Identity Proofs, Resumes)",
  "Asset & Infrastructure Management (Laptops, Labs, Depreciation, Status)",
  "Expense & Petty Cash Tracking (Category Breakdown, Voucher Approvals)",
  "Helpdesk & Ticket Management (Internal & External SLAs, Escalations)",
  "Subscription & Recurring Billing (Monthly/Quarterly/Annual Plans)",
  "Audit Logs & Security Shield (IP Tracing, Timestamped Edits, Anti-Fraud)",
  "Real-Time Mobile App Data Sync (Offline-First Storage, Background Sync)",
];

/* -------------------------------------------------------------
   03. APPLICATION DEVELOPMENT TIERS
------------------------------------------------------------- */
export const APP_DEV_TIERS: ServicePackageItem[] = [
  {
    id: "app-basic-android",
    categoryCode: "APP_DEV",
    categoryName: "Application Development",
    title: "Basic Android App",
    tagline: "Essential Android Presence on Google Play",
    pricingDisplay: "Starting from ₹75,000 + GST",
    billingType: "ONE_TIME",
    timeline: "25 – 40 Working Days",
    idealFor: "Local businesses, catalogs, educational coaching info apps, and booking utilities.",
    deliverables: [
      "Custom UI designed according to Google Material 3 standards",
      "Secure Mobile OTP / Email authentication",
      "Interactive Product / Service catalog with high-speed search",
      "One-click WhatsApp Chat and Call support integration",
      "Push Notifications via Firebase Cloud Messaging",
      "Cloud backend API integration & data synchronization",
      "Google Play Console store listing preparation & deployment assistance",
      "30 days post-launch warranty support",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
  },
  {
    id: "app-pro-android",
    categoryCode: "APP_DEV",
    categoryName: "Application Development",
    title: "Professional Android App",
    tagline: "Feature-Rich Interactive Mobile Experience",
    pricingDisplay: "Starting from ₹1,50,000 + GST",
    billingType: "ONE_TIME",
    timeline: "40 – 60 Working Days",
    idealFor: "E-commerce stores, appointment booking businesses, service aggregators & delivery startups.",
    deliverables: [
      "Native Android architecture (Kotlin / Flutter) for ultra-fluid 60fps performance",
      "Integrated Razorpay / UPI in-app payment gateway",
      "User profile management, saved addresses & order history",
      "Real-time order / service status tracking",
      "Web-based Admin management panel for live data updates",
      "Dynamic in-app banners, coupon codes & promotional notifications",
      "Offline data caching for seamless operation during low connectivity",
      "Google Play Store approval guaranteed submission support",
      "45 days priority post-launch support",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "High Performance",
  },
  {
    id: "app-cross-platform",
    categoryCode: "APP_DEV",
    categoryName: "Application Development",
    title: "Cross-Platform App (Android + iOS)",
    tagline: "Unified Dual-Store App for Maximum Market Reach",
    pricingDisplay: "Starting from ₹2,50,000 + GST",
    billingType: "ONE_TIME",
    timeline: "50 – 75 Working Days",
    idealFor: "National brands, high-growth startups & institutions targeting both iPhone and Android smartphone demographics.",
    deliverables: [
      "Single high-performance codebase in Flutter or React Native",
      "Native look-and-feel conforming to Apple Human Interface & Google Material guidelines",
      "Universal in-app payment checkout (Apple Pay readiness + Razorpay/UPI)",
      "Synchronized Push Notifications across iOS APNs and Android FCM",
      "Deep linking support (universal links to open specific in-app products/screens)",
      "Comprehensive Web Admin Dashboard with analytics & user moderation",
      "Full assistance through both Google Play Store & Apple App Store approval reviews",
      "60 days post-launch hypercare & bug-fix warranty",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Most Popular",
    isPopular: true,
  },
  {
    id: "app-advanced",
    categoryCode: "APP_DEV",
    categoryName: "Application Development",
    title: "Advanced Feature App",
    tagline: "Real-Time Geo-Location, Chat & Complex Business Logic",
    pricingDisplay: "Starting from ₹3,50,000 + GST",
    billingType: "ONE_TIME",
    timeline: "60 – 90 Working Days",
    idealFor: "On-demand hyper-local services, logistics dispatch, ride-sharing, social communities & video learning apps.",
    deliverables: [
      "Live GPS tracking with interactive Google Maps navigation",
      "Real-time in-app chat engine via WebSockets / Supabase Realtime",
      "Audio/Video streaming capabilities with CDN security",
      "Multi-role app architectures (e.g. Customer App + Partner/Driver App)",
      "Automated SMS OTP & WhatsApp authentication fallback",
      "Advanced caching, local SQLite database & background sync workers",
      "Dedicated scalable Node.js / Python cloud backend API",
      "75 days hypercare support with continuous performance monitoring",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
  },
  {
    id: "app-enterprise",
    categoryCode: "APP_DEV",
    categoryName: "Application Development",
    title: "Enterprise Mobile App",
    tagline: "Institutional Mobile Workforce & Secure Customer Ecosystem",
    pricingDisplay: "Starting from ₹5,00,000 + GST",
    billingType: "CUSTOM",
    timeline: "90 – 120+ Working Days",
    idealFor: "Banks, NBFCs, healthcare networks, corporate field forces, and large universities.",
    deliverables: [
      "Enterprise security hardening, code obfuscation, SSL pinning & biometrics login",
      "MDM (Mobile Device Management) enterprise distribution readiness",
      "Offline-first full operational capability with automatic cloud reconciliation",
      "Complex analytical reports, barcode/QR scanner integration & camera OCR",
      "High-concurrency microservices infrastructure handling 100k+ daily active users",
      "Dedicated SLA contract with 4-hour critical incident response",
      "Complete source code repository ownership & developer documentation",
    ],
    paymentStructure: PAYMENT_STRUCTURES.PROJECT_WORK,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Enterprise Flagship",
  },
];

export const APP_DEV_TECH_STACK = [
  { name: "Frontend Frameworks", items: ["Flutter (Dart)", "React Native (TypeScript)", "Android Native (Kotlin)", "iOS Native (SwiftUI)"] },
  { name: "Backend Services", items: ["Node.js / Express", "Python (FastAPI / Django)", "Laravel PHP", "Next.js Edge"] },
  { name: "Databases & Storage", items: ["PostgreSQL", "MySQL", "MongoDB", "Redis Cache", "AWS S3 Bucket"] },
  { name: "Cloud & Realtime", items: ["Firebase (FCM, Auth)", "Supabase", "AWS Cloud Infrastructure", "Docker Microservices"] },
];

/* -------------------------------------------------------------
   04. DIGITAL MARKETING RETAINERS
------------------------------------------------------------- */
export const DIGITAL_MARKETING_RETAINERS: ServicePackageItem[] = [
  {
    id: "dm-starter",
    categoryCode: "DIGITAL_MARKETING",
    categoryName: "Digital Marketing",
    title: "Starter Digital Growth",
    tagline: "Active Social Presence & Local Search Foundation",
    pricingDisplay: "₹15,000 + GST / Month",
    billingType: "MONTHLY",
    priceNote: "Annual: ₹1,62,000 + GST / Year (10% Annual Savings)",
    idealFor: "Startups, local institutes, retail outlets, and independent business owners.",
    deliverables: [
      "12 Custom Social Media Creatives per month",
      "4 Polished Reels / Short Videos per month",
      "Active management across 2 social platforms (Instagram & Facebook)",
      "High-intent caption copywriting & hashtag strategy",
      "Google Business Profile (GBP) optimization & monthly audit",
      "4 Google Business Profile post updates per month",
      "Foundational on-page SEO maintenance for up to 5 core pages",
      "Google Ads campaign setup & weekly monitoring (Ad spend funded directly by client)",
      "Monthly consolidated performance & traffic analytics report",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Starter Squad",
  },
  {
    id: "dm-pro",
    categoryCode: "DIGITAL_MARKETING",
    categoryName: "Digital Marketing",
    title: "Professional Digital Growth",
    tagline: "Multi-Channel Brand Dominance & Lead Generation",
    pricingDisplay: "₹30,000 + GST / Month",
    billingType: "MONTHLY",
    priceNote: "Annual: ₹3,24,000 + GST / Year (10% Annual Savings)",
    idealFor: "Established local institutions, clinical practices, regional retail brands, and B2B suppliers.",
    deliverables: [
      "20 High-impact Social Media Creatives per month",
      "8 Edited Reels / Short Videos with subtitles & motion graphics per month",
      "Social media management across 3 platforms (Instagram, Facebook & LinkedIn)",
      "Strategic trend research & conversion-focused copywriting",
      "Full Google Business Profile management, local citation building & review responses",
      "8 GBP posts / product highlights per month",
      "Comprehensive On-Page SEO optimization for up to 15 pages",
      "Keyword rank tracking across 20 high-value transactional search terms",
      "Google Ads (Search & Call Campaigns) performance management",
      "Meta Ads (Facebook & Instagram lead generation campaigns)",
      "Detailed monthly analytics dashboard covering leads, CPL & conversion metrics",
      "1 Monthly strategic growth review call with senior marketing lead",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Most Popular",
    isPopular: true,
  },
  {
    id: "dm-business-pro",
    categoryCode: "DIGITAL_MARKETING",
    categoryName: "Digital Marketing",
    title: "Business Growth Pro",
    tagline: "High-Velocity Lead Acquisition & Regional Authority",
    pricingDisplay: "₹50,000 + GST / Month",
    billingType: "MONTHLY",
    priceNote: "Annual: ₹5,40,000 + GST / Year (10% Annual Savings)",
    idealFor: "Mid-sized businesses, multi-branch educational academies, hospitals, and real estate developers.",
    deliverables: [
      "30 Custom Visual Creatives per month (daily visual brand presence)",
      "12 Reels / Short Videos with professional voice-over / dynamic editing per month",
      "Comprehensive management across 4 platforms (Instagram, Facebook, LinkedIn, YouTube Shorts)",
      "Advanced brand storytelling, customer success stories & carousel guides",
      "Competitor landscape analysis & quarterly roadmap iteration",
      "Full GBP dominance with local schema & geocoded photo citations",
      "End-to-End SEO (On-page + Technical Core Web Vitals + authoritative backlink building)",
      "2 SEO-optimized thought-leadership blog articles published per month",
      "Full-funnel Google Ads + Meta Ads management with retargeting pixels",
      "Landing page conversion rate optimization (CRO) advisory",
      "Bi-weekly strategic growth sprint review & KPI calibration meetings",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Aggressive Scale",
  },
  {
    id: "dm-corporate",
    categoryCode: "DIGITAL_MARKETING",
    categoryName: "Digital Marketing",
    title: "Corporate Digital Growth",
    tagline: "Dedicated Enterprise Growth Division",
    pricingDisplay: "₹75,000 + GST / Month",
    billingType: "MONTHLY",
    priceNote: "Annual: ₹8,10,000 + GST / Year (10% Annual Savings)",
    idealFor: "Large enterprises, national franchises, institutional universities, and corporate groups.",
    deliverables: [
      "45 Custom Creatives per month across all brand communication channels",
      "16 High-production Short Videos & Reels per month",
      "Omni-channel brand coverage (Instagram, Facebook, LinkedIn, YouTube, X)",
      "Dedicated Full-Time Senior Account Growth Manager",
      "National & hyper-local programmatic SEO campaigns across 50+ keywords",
      "4 In-depth industry whitepapers / SEO blog articles per month",
      "Google Ads + Meta Ads + LinkedIn B2B Executive Ads management",
      "Rigorous multivariate A/B creative & copy testing sprints",
      "Full lead qualification funnel audits & WhatsApp automation sync",
      "Weekly performance reports & monthly C-suite board presentation deck",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Enterprise Squad",
  },
];

/* -------------------------------------------------------------
   05. GRAPHICS & CREATIVE DESIGN (RETAINERS & INDIVIDUAL)
------------------------------------------------------------- */
export const GRAPHICS_RETAINERS: ServicePackageItem[] = [
  {
    id: "gfx-basic",
    categoryCode: "GRAPHICS_DESIGN",
    categoryName: "Graphics & Creative Design",
    title: "Basic Creative Package",
    tagline: "Reliable Monthly Visual Collateral",
    pricingDisplay: "₹8,000 + GST / Month",
    billingType: "MONTHLY",
    idealFor: "Small shops, professional practitioners, and emerging ventures needing steady social visuals.",
    deliverables: [
      "12 Custom Visual Creatives per month (Social posts, promos, announcements)",
      "Standard 48-hour turnaround time per creative request",
      "Up to 2 design review rounds per creative",
      "High-resolution exports formatted for Instagram, WhatsApp & Facebook",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
  },
  {
    id: "gfx-pro",
    categoryCode: "GRAPHICS_DESIGN",
    categoryName: "Graphics & Creative Design",
    title: "Professional Design Package",
    tagline: "Comprehensive Creative Studio Retainer",
    pricingDisplay: "₹15,000 + GST / Month",
    billingType: "MONTHLY",
    idealFor: "Growing businesses, marketing agencies, retail showrooms, and active corporate institutions.",
    deliverables: [
      "25 Custom High-End Creatives per month",
      "4 Specialized Web / Paid Ad Display Banners per month",
      "Priority 24–48 hour turnaround time",
      "Up to 3 design review rounds per creative",
      "Open source files included upon request (PSD, AI, Figma)",
      "Print-ready CMYK files for brochures and standees",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Best Value",
    isPopular: true,
  },
  {
    id: "gfx-corporate",
    categoryCode: "GRAPHICS_DESIGN",
    categoryName: "Graphics & Creative Design",
    title: "Corporate Creative Package",
    tagline: "Dedicated In-House Creative Department",
    pricingDisplay: "₹30,000 + GST / Month",
    billingType: "MONTHLY",
    idealFor: "High-volume corporate houses, multi-brand companies, and institutional event organizers.",
    deliverables: [
      "50 Custom Premium Creatives per month",
      "8 Ad Banners & Promotional campaign sets",
      "4 Custom Motion Graphics / Animated GIFs per month",
      "Dedicated Senior Graphic Artist assigned exclusively to your brand",
      "Rapid 24-hour turnaround for fast-turn market opportunities",
      "Unlimited revisions until 100% satisfaction",
      "Full branding guidelines management & open vector archive repository",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "VIP Studio",
  },
];

export const INDIVIDUAL_GRAPHICS_SERVICES = [
  { service: "Logo Design (3 Concepts + Complete Copyright)", price: "₹4,999 – ₹9,999", timeline: "3–5 Days", deliverable: "3 Vector Concepts, Favicon, PNG, SVG, AI & PDF" },
  { service: "Comprehensive Brand Identity Kit", price: "₹14,999 – ₹29,999", timeline: "7–12 Days", deliverable: "Logo, Typography, Color Palette, Brand Manual & Stationery" },
  { service: "Business Card & Letterhead Suite", price: "₹1,999", timeline: "1–2 Days", deliverable: "Print-ready CMYK + Digital PDF with editable source" },
  { service: "Company Profile / Brochure (Up to 8 Pages)", price: "₹7,999 – ₹14,999", timeline: "4–7 Days", deliverable: "Custom Layout, Visual Copywriting Layout, Print & Interactive PDF" },
  { service: "Company Profile / Brochure (Up to 16 Pages)", price: "₹14,999 – ₹24,999", timeline: "7–14 Days", deliverable: "Multi-department Corporate Prospectus with Infographics" },
  { service: "Product Catalogue Design", price: "₹9,999 – ₹19,999", timeline: "5–10 Days", deliverable: "Categorized SKU grid, pricing tables, high-res mockups" },
  { service: "Social Media Post (Single Creative)", price: "₹499 – ₹799", timeline: "24 Hours", deliverable: "High-impact social banner with caption prompt" },
  { service: "Festival Post Pack (10 National Festivals)", price: "₹3,999", timeline: "3 Days", deliverable: "10 Pre-scheduled branded festival greeting posts" },
  { service: "Roll-up Standee / Outdoor Flex Banner", price: "₹1,499 – ₹2,999", timeline: "1–2 Days", deliverable: "High-resolution vector print file sized to exact feet/inches" },
  { service: "Packaging & Label Design", price: "₹4,999 – ₹11,999", timeline: "5–8 Days", deliverable: "Die-cut template layouts, 3D box mockups, barcode zones" },
  { service: "Flyer / Leaflet Design", price: "₹1,499 – ₹2,499", timeline: "1–2 Days", deliverable: "Single or double-sided promotional hand-out print file" },
  { service: "Infographic Design", price: "₹1,999 – ₹3,999", timeline: "2–3 Days", deliverable: "Complex data simplified into compelling vector charts" },
  { service: "Presentation Deck (Up to 15 Slides)", price: "₹4,999 – ₹9,999", timeline: "3–6 Days", deliverable: "Investor-ready PowerPoint & Figma slide master templates" },
  { service: "Reel / Short Video Editing (Single)", price: "₹999 – ₹1,999", timeline: "24–48 Hours", deliverable: "Dynamic cuts, sound design, animated subtitles & colour grading" },
];

/* -------------------------------------------------------------
   06. CORPORATE COMBO PACKAGES
------------------------------------------------------------- */
export const CORPORATE_COMBO_PACKAGES: ServicePackageItem[] = [
  {
    id: "combo-starter",
    categoryCode: "CORPORATE_COMBO",
    categoryName: "Corporate Combo Packages",
    title: "Corporate Starter",
    tagline: "Essential Combined IT & Marketing Retainer",
    pricingDisplay: "₹35,000 + GST / Month",
    billingType: "MONTHLY",
    priceNote: "Annual Contract: ₹3,78,000 + GST / Year (10% Annual Savings)",
    idealFor: "Startups and emerging businesses needing all-in-one digital presence.",
    deliverables: [
      "Website Hosting & Security AMC (Weekly backups, SSL maintenance, uptime check)",
      "15 Custom Social Media Visual Creatives per month",
      "SEO maintenance for 10 priority keywords",
      "Google Business Profile monthly management & reviews handling",
      "Monthly traffic, keyword rank & performance report",
      "Dedicated WhatsApp & Email technical support channel",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
  },
  {
    id: "combo-growth",
    categoryCode: "CORPORATE_COMBO",
    categoryName: "Corporate Combo Packages",
    title: "Corporate Growth",
    tagline: "Accelerated Market Expansion Engine",
    pricingDisplay: "₹60,000 + GST / Month",
    billingType: "MONTHLY",
    priceNote: "Annual Contract: ₹6,48,000 + GST / Year (10% Annual Savings)",
    idealFor: "Scaling regional enterprises and established companies targeting growth.",
    deliverables: [
      "Website AMC + Minor CMS content updates & feature tweaks",
      "Google & Meta Paid Advertising setup & continuous ROI management",
      "25 Visual Social Creatives + 4 Polished Short Reels per month",
      "SEO ranking sprint for 25 high-intent transactional keywords",
      "WhatsApp lead broadcast assistance & CRM enquiry synchronization",
      "Dedicated Senior Technical & Account Lead",
      "Bi-weekly strategic growth and lead tracking reviews",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Most Popular",
    isPopular: true,
  },
  {
    id: "combo-pro",
    categoryCode: "CORPORATE_COMBO",
    categoryName: "Corporate Combo Packages",
    title: "Corporate Pro",
    tagline: "Full-Stack Tech & Marketing Leadership",
    pricingDisplay: "₹1,00,000 + GST / Month",
    billingType: "MONTHLY",
    priceNote: "Annual Contract: ₹10,80,000 + GST / Year (10% Annual Savings)",
    idealFor: "Established brands, large colleges, clinical networks & market leaders.",
    deliverables: [
      "Continuous Web & App Engineering support (bug fixes, feature additions)",
      "Multi-Channel Paid Ads execution (Google Ads, Meta Ads, LinkedIn Ads)",
      "Daily Social Content (40 Creatives + 8 Reels per month)",
      "Aggressive Technical SEO, speed optimization & authority backlink sprints",
      "Custom CRM pipeline automation and lead notification workflows",
      "High-Priority 8-hour Corporate SLA response window",
      "Weekly strategic KPI review meeting with director-level escalations",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "High Growth",
  },
  {
    id: "combo-enterprise",
    categoryCode: "CORPORATE_COMBO",
    categoryName: "Corporate Combo Packages",
    title: "Enterprise Digital Partner",
    tagline: "Dedicated Outsourced Technology & Creative Wing",
    pricingDisplay: "From ₹1,50,000 + GST / Month",
    billingType: "CUSTOM",
    priceNote: "Annual Contract: ₹16,20,000 + GST / Year onwards",
    idealFor: "Large institutional groups, universities, manufacturing conglomerates, and international brands.",
    deliverables: [
      "Dedicated Full-Stack Developer & Senior UI/UX Designer dedicated to your team",
      "Dedicated Performance Marketing Strategist and copywriter",
      "Full Cloud VPS & Disaster Recovery hosting management (AWS / DigitalOcean)",
      "Continuous custom internal tooling, ERP improvements & automation sprints",
      "Formal 99.9% Uptime SLA with 2-hour emergency escalation hotline",
      "Direct C-Level & Executive Director escalation access",
      "On-site quarterly strategic review & architecture audit sessions",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Enterprise Partner",
  },
];

/* -------------------------------------------------------------
   07. AMC, CLOUD & HOSTING SERVICES
------------------------------------------------------------- */
export const WEBSITE_AMC_PACKAGES: ServicePackageItem[] = [
  {
    id: "amc-web-basic",
    categoryCode: "AMC_SUPPORT",
    categoryName: "Website Maintenance",
    title: "Basic Website AMC",
    tagline: "Essential Security & Backup Shield",
    pricingDisplay: "₹12,000 + GST / Year",
    billingType: "ANNUAL",
    idealFor: "Small informative websites needing reliable uptime and peace of mind.",
    deliverables: [
      "Monthly core engine & plugin updates",
      "Weekly off-site automated cloud backups",
      "24/7 automated uptime monitoring",
      "SSL certificate renewal assistance",
      "Emergency malware removal & basic security patches",
      "Standard email ticket support (24–48h response)",
    ],
    paymentStructure: PAYMENT_STRUCTURES.ANNUAL_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
  },
  {
    id: "amc-web-business",
    categoryCode: "AMC_SUPPORT",
    categoryName: "Website Maintenance",
    title: "Business Website AMC",
    tagline: "Proactive Security & Content Management",
    pricingDisplay: "₹25,000 + GST / Year",
    billingType: "ANNUAL",
    idealFor: "Corporate business websites with regular content changes.",
    deliverables: [
      "All Basic AMC features included",
      "Up to 3 hours of monthly developer time for text, image & banner updates",
      "Bi-weekly security audits & vulnerability scanning",
      "Speed optimization checks & database cleanups",
      "Priority 12–24h response time SLA",
    ],
    paymentStructure: PAYMENT_STRUCTURES.ANNUAL_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Recommended",
    isPopular: true,
  },
  {
    id: "amc-web-pro",
    categoryCode: "AMC_SUPPORT",
    categoryName: "Website Maintenance",
    title: "Professional Website AMC",
    tagline: "High-Traffic E-Commerce & Portal Support",
    pricingDisplay: "₹50,000 + GST / Year",
    billingType: "ANNUAL",
    idealFor: "Active e-commerce stores, membership sites & high-traffic platforms.",
    deliverables: [
      "All Business AMC features included",
      "Up to 8 hours of monthly developer time for layout and functional tweaks",
      "Payment gateway checkout testing & webhook health monitoring",
      "Daily automated cloud backups with 1-click restore",
      "Dedicated WhatsApp engineer support (4–8h response)",
    ],
    paymentStructure: PAYMENT_STRUCTURES.ANNUAL_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
  },
  {
    id: "amc-web-enterprise",
    categoryCode: "AMC_SUPPORT",
    categoryName: "Website Maintenance",
    title: "Enterprise Website AMC",
    tagline: "Mission-Critical 24/7 Engineering Shield",
    pricingDisplay: "Starting from ₹1,00,000 + GST / Year",
    billingType: "ANNUAL",
    idealFor: "Large corporate portals, university exam portals & mission-critical sites.",
    deliverables: [
      "Continuous server telemetry, real-time APM monitoring & DDoS protection",
      "Unlimited bug fixes and 20 hours monthly feature enhancement sprints",
      "Disaster recovery failover setup across multi-region cloud servers",
      "24/7 immediate critical emergency escalation hotline (1-hour response)",
      "Direct account manager assigned",
    ],
    paymentStructure: PAYMENT_STRUCTURES.ANNUAL_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Enterprise SLA",
  },
];

export const SOFTWARE_APP_AMC_PACKAGES: ServicePackageItem[] = [
  {
    id: "amc-soft-basic",
    categoryCode: "AMC_SUPPORT",
    categoryName: "Software & App AMC",
    title: "Basic Software/App Support",
    tagline: "Stability & Bug Rectification",
    pricingDisplay: "₹10,000 + GST / Month",
    billingType: "MONTHLY",
    idealFor: "Standard business software with steady user workflows.",
    deliverables: [
      "Regular cloud database index optimization and cleanup",
      "Third-party API health checks (SMS, Email, Payment Gateway)",
      "Standard bug-fixing & OS compatibility updates",
      "24–48 hour response time SLA",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
  },
  {
    id: "amc-soft-pro",
    categoryCode: "AMC_SUPPORT",
    categoryName: "Software & App AMC",
    title: "Professional Software/App Support",
    tagline: "Store Compliance & Active Developer Allocation",
    pricingDisplay: "₹25,000 + GST / Month",
    billingType: "MONTHLY",
    idealFor: "High-volume operational ERPs & active Play Store/App Store applications.",
    deliverables: [
      "All Basic features included",
      "Google Play & Apple App Store annual compliance policy updates",
      "Up to 15 developer hours for minor functional extensions",
      "Database read-replica monitoring and cache tuning",
      "Priority 8–12 hour response time SLA with WhatsApp group",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Popular",
    isPopular: true,
  },
  {
    id: "amc-soft-enterprise",
    categoryCode: "AMC_SUPPORT",
    categoryName: "Software & App AMC",
    title: "Enterprise Software/App Support",
    tagline: "Dedicated Cloud DevOps & Zero-Downtime Guarantee",
    pricingDisplay: "Starting from ₹50,000 + GST / Month",
    billingType: "CUSTOM",
    idealFor: "Large institutional SaaS platforms, financial systems & university ERPs.",
    deliverables: [
      "Dedicated Full-Stack developer sprint allocation",
      "24/7 automated synthetic user journey monitoring",
      "Disaster recovery replication & sub-hour RTO guarantee",
      "2–4 hour critical escalation response time with direct architect access",
    ],
    paymentStructure: PAYMENT_STRUCTURES.MONTHLY_RETAINER,
    commercialTerms: COMMON_COMMERCIAL_TERMS,
    badge: "Enterprise",
  },
];

export const CLOUD_HOSTING_SERVICES = [
  { service: "Domain Registration (.com / .in / .co.in / .org)", price: "₹1,000 – ₹2,500 + GST / Year", period: "Annual", desc: "DNS management, WHOIS privacy protection & domain locking." },
  { service: "Basic Cloud Shared Hosting", price: "₹4,999 + GST / Year", period: "Annual", desc: "SSD storage, unlimited bandwidth, free SSL & daily automated backup." },
  { service: "Business Cloud Hosting (High RAM/CPU)", price: "₹9,999 + GST / Year", period: "Annual", desc: "Isolated container resources, LiteSpeed caching, Redis & 99.9% uptime." },
  { service: "Premium Cloud Managed Server", price: "₹24,999 + GST / Year", period: "Annual", desc: "Dedicated resources, staging environment, firewall & priority bandwidth." },
  { service: "Dedicated VPS Server (DigitalOcean / AWS / Linode)", price: "Starting from ₹3,000 + GST / Month", period: "Monthly", desc: "Root access, scalable vCPUs, automated snapshot backups & custom OS." },
  { service: "Google Workspace / M365 Business Email Setup", price: "Starting from ₹2,500 + GST one-time + user fees", period: "Setup + Subscription", desc: "SPF, DKIM & DMARC verification for 100% inbox delivery and no spam." },
  { service: "Cloud Disaster Recovery & Offsite Backup", price: "Starting from ₹5,000 + GST / Year", period: "Annual", desc: "Encrypted AES-256 cloud snapshots stored in isolated geographic locations." },
];

/* Helper function to get any package by ID */
export function getPackageById(id: string): ServicePackageItem | undefined {
  const allPackages: ServicePackageItem[] = [
    ...WEBSITE_PACKAGES,
    ...SOFTWARE_TIERS,
    ...APP_DEV_TIERS,
    ...DIGITAL_MARKETING_RETAINERS,
    ...GRAPHICS_RETAINERS,
    ...CORPORATE_COMBO_PACKAGES,
    ...WEBSITE_AMC_PACKAGES,
    ...SOFTWARE_APP_AMC_PACKAGES,
  ];
  return allPackages.find((pkg) => pkg.id === id);
}
